apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: od3toin5m-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:4b0ab4e2e4a4cfb89a79e6777cb4c79b8a074663@sha256:73eeceb2ea80c5895437da4e19aa40e1b24e74dbd1f177dfcae015e8380c9314
          name: container-image
